package com.clean.it.service;

import com.clean.it.domain.Payment;import com.clean.it.repository.PaymentEventRepository;import com.clean.it.repository.PaymentRepository;import com.clean.it.repository.ReservationRepository;import com.stripe.exception.EventDataObjectDeserializationException;import com.stripe.model.Event;import com.stripe.model.EventDataObjectDeserializer;import com.stripe.model.PaymentIntent;import com.stripe.model.StripeObject;import org.slf4j.Logger;import org.slf4j.LoggerFactory;import org.springframework.stereotype.Service;import org.springframework.transaction.PlatformTransactionManager;import org.springframework.transaction.support.TransactionTemplate;import java.time.Duration;import java.time.Instant;import java.util.Locale;import java.util.Objects;import java.util.Set;

@Service public class StripeWebhookService {
 private static final Logger log=LoggerFactory.getLogger(StripeWebhookService.class);private static final Duration LEASE=Duration.ofMinutes(15);private static final int MAX=1000;private static final Set<String> EVENTS=Set.of("payment_intent.processing","payment_intent.succeeded","payment_intent.payment_failed","payment_intent.canceled");
 private final PaymentEventRepository events;private final PaymentRepository payments;private final ReservationRepository reservations;private final MarketplaceNotificationService notifications;private final MarketplaceSettlementService settlements;private final TransactionTemplate tx;
 public StripeWebhookService(PaymentEventRepository events,PaymentRepository payments,ReservationRepository reservations,MarketplaceNotificationService notifications,MarketplaceSettlementService settlements,PlatformTransactionManager manager){this.events=events;this.payments=payments;this.reservations=reservations;this.notifications=notifications;this.settlements=settlements;this.tx=new TransactionTemplate(manager);}
 public boolean process(Event event){Instant now=Instant.now(),created=event.getCreated()==null?now:Instant.ofEpochSecond(event.getCreated());Boolean claimed=tx.execute(s->events.claim(event.getId(),event.getType(),created,now,now.minus(LEASE))>0);if(!Boolean.TRUE.equals(claimed))return false;try{tx.executeWithoutResult(s->processClaimed(event));return true;}catch(RuntimeException ex){tx.executeWithoutResult(s->events.markFailed(event.getId(),safe(ex)));throw ex;}}
 private void processClaimed(Event event){if(EVENTS.contains(event.getType())){PaymentIntent intent=paymentIntent(event);payments.findByStripePaymentIntentId(intent.getId()).ifPresentOrElse(payment->{events.linkPayment(event.getId(),payment.getId(),intent.getId());update(payment,intent);Payment saved=payments.save(payment);settlements.syncPaymentStatus(saved);reservations.findById(saved.getReservationId()).ifPresent(r->notifications.paymentStatus(saved,r));},()->log.warn("Stripe event {} references unknown PaymentIntent {}",event.getId(),intent.getId()));}else log.info("Ignoring unsupported Stripe event type {} ({})",event.getType(),event.getId());if(events.markProcessed(event.getId(),Instant.now())!=1)throw new IllegalStateException("Stripe event processing lease was lost");}
 private PaymentIntent paymentIntent(Event event){EventDataObjectDeserializer d=event.getDataObjectDeserializer();StripeObject o=d.getObject().orElseGet(()->unsafe(d,event));if(!(o instanceof PaymentIntent i))throw new IllegalArgumentException("Stripe event does not contain a PaymentIntent");return i;}
 private StripeObject unsafe(EventDataObjectDeserializer d,Event e){try{log.warn("Unsafe Stripe event deserialization for API version {} and event {}",e.getApiVersion(),e.getId());return d.deserializeUnsafe();}catch(EventDataObjectDeserializationException ex){throw new IllegalArgumentException("Stripe event payload could not be deserialized",ex);}}
 private void update(Payment p,PaymentIntent i){String currency=i.getCurrency()==null?null:i.getCurrency().toLowerCase(Locale.ROOT),expected=p.getCurrency()==null?null:p.getCurrency().toLowerCase(Locale.ROOT);if(!Objects.equals(p.getAmountCents(),i.getAmount())||!Objects.equals(expected,currency))throw new IllegalStateException("Stripe payment amount or currency does not match the reservation");p.setStatus(i.getStatus());p.setRawJson(i.toJson());if(i.getClientSecret()!=null)p.setClientSecret(i.getClientSecret());}
 private String safe(RuntimeException ex){String m=ex.getMessage();if(m==null||m.isBlank())m=ex.getClass().getSimpleName();return m.length()<=MAX?m:m.substring(0,MAX);}
}
