package com.clean.it;

import org.flywaydb.core.Flyway;import org.junit.jupiter.api.Test;import org.testcontainers.junit.jupiter.Container;import org.testcontainers.junit.jupiter.Testcontainers;import org.testcontainers.postgresql.PostgreSQLContainer;import java.sql.*;import static org.assertj.core.api.Assertions.*;

@Testcontainers(disabledWithoutDocker=true)
class MigrationPostgresTest {
 @Container static final PostgreSQLContainer POSTGRES=new PostgreSQLContainer("postgres:16-alpine");
 @Test void migrationsRunAndEnforceMarketplaceNotificationAndOperationsInvariants() throws Exception{Flyway flyway=Flyway.configure().dataSource(POSTGRES.getJdbcUrl(),POSTGRES.getUsername(),POSTGRES.getPassword()).locations("classpath:db/migration").load();assertThat(flyway.migrate().migrationsExecuted).isGreaterThanOrEqualTo(7);try(Connection c=DriverManager.getConnection(POSTGRES.getJdbcUrl(),POSTGRES.getUsername(),POSTGRES.getPassword())){assertThat(count(c,"SELECT count(*) FROM service_types WHERE active=true")).isEqualTo(3);long clientId=insertUser(c,"client-sub","client@example.com"),cleanerId=insertUser(c,"cleaner-sub","cleaner@example.com"),adminId=insertUser(c,"admin-sub","admin@example.com");insertNotification(c,clientId,"reservation:1:created:email");insertNotification(c,clientId,"reservation:1:created:email");assertThat(count(c,"SELECT count(*) FROM notification_outbox WHERE event_key='reservation:1:created:email'")).isEqualTo(1);insertCleaner(c,cleanerId,"cleaner@example.com");long serviceId=serviceTypeId(c,"STANDARD");insertOffering(c,cleanerId,serviceId,1800);assertThatThrownBy(()->insertOffering(c,cleanerId,serviceId,2000)).isInstanceOf(SQLException.class).hasMessageContaining("uk_cleaner_service_offering");insertServiceArea(c,cleanerId,"ES","28");assertThatThrownBy(()->insertServiceArea(c,cleanerId,"ES","28")).isInstanceOf(SQLException.class).hasMessageContaining("uk_cleaner_service_area");long jobId=insertJob(c,clientId);long reservationId=insertReservation(c,jobId,clientId,cleanerId);long paymentId=insertPayment(c,reservationId,"pi_test_1");assertThatThrownBy(()->insertPayment(c,reservationId,"pi_test_2")).isInstanceOf(SQLException.class).hasMessageContaining("uk_payments_reservation");long connectId=insertConnectAccount(c,cleanerId,"acct_test_1");assertThatThrownBy(()->insertConnectAccount(c,cleanerId,"acct_test_2")).isInstanceOf(SQLException.class).hasMessageContaining("uk_cleaner_connect_cleaner");insertAudit(c,adminId,"op-1");assertThatThrownBy(()->insertAudit(c,adminId,"op-1")).isInstanceOf(SQLException.class).hasMessageContaining("uk_admin_audit_idempotency");insertSettlement(c,reservationId,paymentId,cleanerId,connectId,5000,750,4250);assertThat(count(c,"SELECT count(*) FROM marketplace_settlements WHERE reservation_id="+reservationId+" AND platform_fee_cents=750 AND provider_amount_cents=4250")).isEqualTo(1);assertThatThrownBy(()->updateSettlementAmounts(c,reservationId,751,4250)).isInstanceOf(SQLException.class).hasMessageContaining("chk_settlement_amounts");}}
 private long count(Connection c,String q)throws SQLException{try(var s=c.prepareStatement(q);var r=s.executeQuery()){r.next();return r.getLong(1);}}
 private long insertUser(Connection c,String subject,String email)throws SQLException{try(var s=c.prepareStatement("INSERT INTO user_accounts(issuer,subject,email,roles) VALUES ('https://issuer.example/',?,?, '') RETURNING id")){s.setString(1,subject);s.setString(2,email);try(var r=s.executeQuery()){r.next();return r.getLong(1);}}}
 private void insertNotification(Connection c,long user,String key)throws SQLException{try(var s=c.prepareStatement("INSERT INTO notification_outbox(event_key,event_type,recipient_user_id,channel,subject,body,status,available_at) VALUES (?,'RESERVATION_CREATED',?,'EMAIL','Reserva','Confirmada','PENDING',NOW()) ON CONFLICT(event_key) DO NOTHING")){s.setString(1,key);s.setLong(2,user);s.executeUpdate();}}
 private void insertCleaner(Connection c,long user,String email)throws SQLException{try(var s=c.prepareStatement("INSERT INTO cleaners(user_id,email,name,rating) VALUES (?,?,'Cleaner',0)")){s.setLong(1,user);s.setString(2,email);s.executeUpdate();}}
 private long serviceTypeId(Connection c,String code)throws SQLException{try(var s=c.prepareStatement("SELECT id FROM service_types WHERE code=?")){s.setString(1,code);try(var r=s.executeQuery()){r.next();return r.getLong(1);}}}
 private void insertOffering(Connection c,long cleaner,long service,long rate)throws SQLException{try(var s=c.prepareStatement("INSERT INTO cleaner_service_offerings(cleaner_id,service_type_id,hourly_rate_cents,active) VALUES (?,?,?,true)")){s.setLong(1,cleaner);s.setLong(2,service);s.setLong(3,rate);s.executeUpdate();}}
 private void insertServiceArea(Connection c,long cleaner,String country,String prefix)throws SQLException{try(var s=c.prepareStatement("INSERT INTO cleaner_service_areas(cleaner_id,country_code,postal_code_prefix) VALUES (?,?,?)")){s.setLong(1,cleaner);s.setString(2,country);s.setString(3,prefix);s.executeUpdate();}}
 private long insertJob(Connection c,long client)throws SQLException{try(var s=c.prepareStatement("INSERT INTO jobs(client_id,client_email,title,status,price_cents) VALUES (?,'client@example.com','Test','OPEN',5000) RETURNING id")){s.setLong(1,client);try(var r=s.executeQuery()){r.next();return r.getLong(1);}}}
 private long insertReservation(Connection c,long job,long client,long cleaner)throws SQLException{try(var s=c.prepareStatement("INSERT INTO reservations(job_id,client_id,client_email,cleaner_id,cleaner_email,start_at,end_at,duration_minutes,agreed_amount_cents,currency,status,version) VALUES (?,?,'client@example.com',?,'cleaner@example.com','2030-01-01 10:00:00+00','2030-01-01 12:00:00+00',120,5000,'eur','SCHEDULED',0) RETURNING id")){s.setLong(1,job);s.setLong(2,client);s.setLong(3,cleaner);try(var r=s.executeQuery()){r.next();return r.getLong(1);}}}
 private long insertPayment(Connection c,long reservation,String pi)throws SQLException{try(var s=c.prepareStatement("INSERT INTO payments(reservation_id,amount_cents,currency,stripe_payment_intent_id,status,version,created_at,updated_at) VALUES (?,5000,'eur',?,'requires_payment_method',0,NOW(),NOW()) RETURNING id")){s.setLong(1,reservation);s.setString(2,pi);try(var r=s.executeQuery()){r.next();return r.getLong(1);}}}
 private long insertConnectAccount(Connection c,long cleaner,String account)throws SQLException{try(var s=c.prepareStatement("INSERT INTO cleaner_connect_accounts(cleaner_id,stripe_account_id,country_code,onboarding_status,details_submitted,charges_enabled,payouts_enabled) VALUES (?,?,'ES','READY',true,true,true) RETURNING id")){s.setLong(1,cleaner);s.setString(2,account);try(var r=s.executeQuery()){r.next();return r.getLong(1);}}}
 private void insertAudit(Connection c,long admin,String key)throws SQLException{try(var s=c.prepareStatement("INSERT INTO admin_audit_log(actor_user_id,action,target_type,target_id,idempotency_key,details) VALUES (?,'BLOCK_USER','USER','1',?,'test')")){s.setLong(1,admin);s.setString(2,key);s.executeUpdate();}}
 private void insertSettlement(Connection c,long reservation,long payment,long cleaner,long account,long gross,long fee,long provider)throws SQLException{try(var s=c.prepareStatement("INSERT INTO marketplace_settlements(reservation_id,payment_id,cleaner_id,connect_account_id,gross_cents,platform_fee_cents,provider_amount_cents,currency,status) VALUES (?,?,?,?,?,?,?,'eur','PENDING')")){s.setLong(1,reservation);s.setLong(2,payment);s.setLong(3,cleaner);s.setLong(4,account);s.setLong(5,gross);s.setLong(6,fee);s.setLong(7,provider);s.executeUpdate();}}
 private void updateSettlementAmounts(Connection c,long reservation,long fee,long provider)throws SQLException{try(var s=c.prepareStatement("UPDATE marketplace_settlements SET platform_fee_cents=?,provider_amount_cents=? WHERE reservation_id=?")){s.setLong(1,fee);s.setLong(2,provider);s.setLong(3,reservation);s.executeUpdate();}}
}
