package com.clean.it.service;

import com.clean.it.domain.*;import com.clean.it.dto.AdminDtos.*;import com.clean.it.repository.*;import org.junit.jupiter.api.Test;import java.util.Optional;import static org.assertj.core.api.Assertions.*;import static org.mockito.Mockito.*;

class AdminOperationsServiceTest {
 @Test void adminCannotBlockOwnAccount(){Deps d=new Deps();assertThatThrownBy(()->service(d).block(9L,9L,new AdminActionRequest("op-1","test"))).isInstanceOf(IllegalArgumentException.class).hasMessageContaining("own");verifyNoInteractions(d.users,d.audit);}
 @Test void blockIsAuditedAndIdempotent(){Deps d=new Deps();UserAccount user=new UserAccount();user.setId(4L);when(d.users.findById(4L)).thenReturn(Optional.of(user));when(d.audit.findByIdempotencyKey("op-1")).thenReturn(Optional.empty());service(d).block(9L,4L,new AdminActionRequest("op-1","fraud review"));assertThat(user.getBlockedAt()).isNotNull();assertThat(user.getBlockedByUserId()).isEqualTo(9L);verify(d.audit).save(argThat(a->"BLOCK_USER".equals(a.getAction())&&"op-1".equals(a.getIdempotencyKey())&&"4".equals(a.getTargetId())));AdminAuditLog prior=new AdminAuditLog();prior.setAction("BLOCK_USER");prior.setTargetType("USER");prior.setTargetId("4");prior.setIdempotencyKey("op-1");reset(d.users,d.audit);when(d.audit.findByIdempotencyKey("op-1")).thenReturn(Optional.of(prior));service(d).block(9L,4L,new AdminActionRequest("op-1","retry"));verifyNoInteractions(d.users);verify(d.audit,never()).save(any());}
 @Test void hidingReviewRecalculatesCleanerRating(){Deps d=new Deps();Review review=new Review();review.setId(3L);review.setCleanerId(22L);Cleaner cleaner=new Cleaner();cleaner.setUserId(22L);when(d.reviews.findById(3L)).thenReturn(Optional.of(review));when(d.reviews.averageRating(22L)).thenReturn(4.0);when(d.cleaners.findFirstByUserId(22L)).thenReturn(Optional.of(cleaner));service(d).moderateReview(9L,3L,new ReviewModerationRequest("mod-1","HIDDEN","abuse"));assertThat(review.getModerationStatus()).isEqualTo("HIDDEN");assertThat(cleaner.getRating()).isEqualTo(4.0);verify(d.audit).save(argThat(a->"MODERATE_REVIEW".equals(a.getAction())));}
 private AdminOperationsService service(Deps d){return new AdminOperationsService(d.users,d.cleaners,d.jobs,d.reservations,d.payments,d.reviews,d.paymentEvents,d.audit,d.settlements,d.payouts,d.paymentService,d.notifications);}
 private static class Deps{final UserAccountRepository users=mock(UserAccountRepository.class);final CleanerRepository cleaners=mock(CleanerRepository.class);final JobRepository jobs=mock(JobRepository.class);final ReservationRepository reservations=mock(ReservationRepository.class);final PaymentRepository payments=mock(PaymentRepository.class);final ReviewRepository reviews=mock(ReviewRepository.class);final PaymentEventRepository paymentEvents=mock(PaymentEventRepository.class);final AdminAuditLogRepository audit=mock(AdminAuditLogRepository.class);final MarketplaceSettlementRepository settlements=mock(MarketplaceSettlementRepository.class);final StripePayoutRepository payouts=mock(StripePayoutRepository.class);final PaymentService paymentService=mock(PaymentService.class);final MarketplaceNotificationService notifications=mock(MarketplaceNotificationService.class);}
}
