package com.clean.it.service;

import com.clean.it.domain.Cleaner;import com.clean.it.domain.CleanerConnectAccount;import com.clean.it.dto.ConnectDtos.OnboardingRequest;import com.clean.it.repository.CleanerConnectAccountRepository;import com.clean.it.repository.CleanerRepository;import org.junit.jupiter.api.Test;import java.util.Optional;import static org.assertj.core.api.Assertions.*;import static org.mockito.ArgumentMatchers.*;import static org.mockito.Mockito.*;

class ConnectAccountServiceTest {
 @Test void createsOneConnectedAccountAndReturnsHostedOnboarding(){var accounts=mock(CleanerConnectAccountRepository.class);var cleaners=mock(CleanerRepository.class);var stripe=mock(StripeConnectGateway.class);var policy=mock(MarketplacePaymentPolicy.class);Cleaner cleaner=new Cleaner();cleaner.setUserId(22L);when(cleaners.findFirstByUserId(22L)).thenReturn(Optional.of(cleaner));when(policy.enabled()).thenReturn(true);when(stripe.isConfigured()).thenReturn(true);when(accounts.findByCleanerId(22L)).thenReturn(Optional.empty());var snapshot=new StripeConnectGateway.ConnectedAccountSnapshot("acct_1","ES",false,false,false,"{}");when(stripe.createConnectedAccount("cleaner@example.com","ES",22L,"cleaner:22:connect-account:v1")).thenReturn(snapshot);when(accounts.save(any(CleanerConnectAccount.class))).thenAnswer(i->{CleanerConnectAccount a=i.getArgument(0);a.setId(5L);return a;});when(stripe.retrieveConnectedAccount("acct_1")).thenReturn(snapshot);when(stripe.createOnboardingLink(eq("acct_1"),eq("https://cleanit.es/refresh"),eq("https://cleanit.es/return"),startsWith("cleaner:22:connect-onboarding:"))).thenReturn("https://connect.stripe.test/onboard");ConnectAccountService service=new ConnectAccountService(accounts,cleaners,stripe,policy,"https://cleanit.es/refresh","https://cleanit.es/return");var response=service.onboarding(22L,"cleaner@example.com",new OnboardingRequest("es"));assertThat(response.onboardingUrl()).startsWith("https://connect.stripe.test");verify(policy).requireAllowedCountry("ES");verify(stripe).createConnectedAccount("cleaner@example.com","ES",22L,"cleaner:22:connect-account:v1");}
 @Test void readyAccountRequiresPayoutsAndDetails(){var accounts=mock(CleanerConnectAccountRepository.class);var cleaners=mock(CleanerRepository.class);var stripe=mock(StripeConnectGateway.class);var policy=mock(MarketplacePaymentPolicy.class);when(policy.enabled()).thenReturn(true);CleanerConnectAccount a=new CleanerConnectAccount();a.setCleanerId(22L);a.setStripeAccountId("acct_1");a.setDetailsSubmitted(true);a.setPayoutsEnabled(true);when(accounts.findByCleanerId(22L)).thenReturn(Optional.of(a));assertThat(new ConnectAccountService(accounts,cleaners,stripe,policy,"","").requireReady(22L)).isSameAs(a);}
 @Test void countryMustBeExplicitlyAllowed(){var accounts=mock(CleanerConnectAccountRepository.class);var cleaners=mock(CleanerRepository.class);var stripe=mock(StripeConnectGateway.class);var policy=mock(MarketplacePaymentPolicy.class);Cleaner cleaner=new Cleaner();cleaner.setUserId(22L);when(cleaners.findFirstByUserId(22L)).thenReturn(Optional.of(cleaner));when(policy.enabled()).thenReturn(true);when(stripe.isConfigured()).thenReturn(true);doThrow(new IllegalArgumentException("Country is not enabled")).when(policy).requireAllowedCountry("US");ConnectAccountService service=new ConnectAccountService(accounts,cleaners,stripe,policy,"x","y");assertThatThrownBy(()->service.onboarding(22L,"c@example.com",new OnboardingRequest("US"))).isInstanceOf(IllegalArgumentException.class).hasMessageContaining("Country");verify(stripe,never()).createConnectedAccount(anyString(),anyString(),anyLong(),anyString());}
}
