package com.clean.it.service.impl;

import com.clean.it.domain.CleanerConnectAccount;import com.clean.it.domain.Payment;import com.clean.it.domain.Reservation;import com.clean.it.dto.AppDtos.PaymentRequest;import com.clean.it.repository.JobRepository;import com.clean.it.repository.PaymentRepository;import com.clean.it.repository.ReservationRepository;import com.clean.it.service.*;import com.clean.it.service.StripeGateway.IntentSnapshot;import com.clean.it.service.StripeGateway.RefundSnapshot;import org.junit.jupiter.api.Test;import java.util.Optional;import static org.assertj.core.api.Assertions.assertThat;import static org.mockito.ArgumentMatchers.any;import static org.mockito.Mockito.*;

class PaymentServiceImplTest {
 @Test void legacyFlowKeepsStablePaymentIntentIdempotencyKeyWhenConnectDisabled(){Deps d=deps(false);Reservation r=reservation(42L);when(d.reservations.findLockedById(42L)).thenReturn(Optional.of(r));when(d.payments.findFirstByReservationId(42L)).thenReturn(Optional.empty());when(d.stripe.isConfigured()).thenReturn(true);when(d.stripe.publishableKey()).thenReturn("pk_test");when(d.stripe.createPaymentIntent(5_000L,"eur",42L,"reservation:42:payment-intent:v1")).thenReturn(new IntentSnapshot("pi_123","secret","requires_payment_method","{}"));when(d.payments.save(any(Payment.class))).thenAnswer(i->i.getArgument(0));var response=service(d).createPaymentIntent(11L,request(42L));assertThat(response.getAmountCents()).isEqualTo(5_000L);assertThat(response.getClientSecret()).isEqualTo("secret");verify(d.stripe).createPaymentIntent(5_000L,"eur",42L,"reservation:42:payment-intent:v1");verifyNoInteractions(d.connect,d.settlements);}

 @Test void connectedFlowCalculatesFeeServerSideAndPersistsSettlement(){Deps d=deps(true);Reservation r=reservation(42L);CleanerConnectAccount account=new CleanerConnectAccount();account.setId(4L);account.setCleanerId(22L);account.setStripeAccountId("acct_1");account.setDetailsSubmitted(true);account.setPayoutsEnabled(true);when(d.reservations.findLockedById(42L)).thenReturn(Optional.of(r));when(d.payments.findFirstByReservationId(42L)).thenReturn(Optional.empty());when(d.stripe.isConfigured()).thenReturn(true);when(d.stripe.publishableKey()).thenReturn("pk_test");when(d.policy.platformFee(5_000L)).thenReturn(750L);when(d.policy.onBehalfOf()).thenReturn(false);when(d.connect.requireReady(22L)).thenReturn(account);when(d.stripe.createDestinationPaymentIntent(5_000L,"eur",42L,"acct_1",750L,false,"reservation:42:marketplace-payment-intent:v1")).thenReturn(new IntentSnapshot("pi_connect","secret_connect","requires_payment_method","{}"));when(d.payments.save(any(Payment.class))).thenAnswer(i->{Payment p=i.getArgument(0);p.setId(9L);return p;});service(d).createPaymentIntent(11L,request(42L));verify(d.payments).save(argThat(p->Long.valueOf(750L).equals(p.getPlatformFeeCents())&&Long.valueOf(4_250L).equals(p.getProviderAmountCents())&&"acct_1".equals(p.getStripeDestinationAccount())));verify(d.settlements).prepare(eq(r),any(Payment.class),eq(account),eq(750L));verify(d.stripe).createDestinationPaymentIntent(5_000L,"eur",42L,"acct_1",750L,false,"reservation:42:marketplace-payment-intent:v1");}

 @Test void connectedRefundUsesExplicitTransferAndFeePolicy(){Deps d=deps(true);Payment p=payment("succeeded");p.setStripeDestinationAccount("acct_1");Reservation r=reservation(42L);when(d.payments.findFirstByReservationId(42L)).thenReturn(Optional.of(p));when(d.payments.save(p)).thenReturn(p);when(d.reservations.findById(42L)).thenReturn(Optional.of(r));when(d.stripe.isConfigured()).thenReturn(true);when(d.policy.refundReverseTransfer()).thenReturn(true);when(d.policy.refundApplicationFee()).thenReturn(false);when(d.stripe.refundDestinationPaymentIntent("pi_existing","reservation:42:refund:v1",true,false)).thenReturn(new RefundSnapshot("re_1","succeeded","{}"));service(d).cancelOrRefundReservationPayment(42L);assertThat(p.getStatus()).isEqualTo("refunded");verify(d.settlements).markRefunded(p);verify(d.notifications).paymentStatus(p,r);}

 @Test void existingIntentIsReused(){Deps d=deps(false);Reservation r=reservation(42L);Payment p=payment("requires_payment_method");p.setClientSecret("secret_existing");when(d.reservations.findLockedById(42L)).thenReturn(Optional.of(r));when(d.payments.findFirstByReservationId(42L)).thenReturn(Optional.of(p));when(d.stripe.isConfigured()).thenReturn(true);when(d.stripe.publishableKey()).thenReturn("pk_test");var response=service(d).createPaymentIntent(11L,request(42L));assertThat(response.getPaymentId()).isEqualTo(7L);verify(d.stripe,never()).createPaymentIntent(anyLong(),anyString(),anyLong(),anyString());verify(d.stripe,never()).createDestinationPaymentIntent(anyLong(),anyString(),anyLong(),anyString(),anyLong(),anyBoolean(),anyString());}

 private PaymentServiceImpl service(Deps d){return new PaymentServiceImpl(d.payments,d.reservations,d.jobs,d.stripe,d.notifications,d.policy,d.connect,d.settlements);}
 private Deps deps(boolean enabled){Deps d=new Deps();when(d.policy.enabled()).thenReturn(enabled);return d;}
 private PaymentRequest request(long id){PaymentRequest r=new PaymentRequest();r.setReservationId(id);return r;}
 private Reservation reservation(long id){Reservation r=new Reservation();r.setId(id);r.setJobId(3L);r.setClientId(11L);r.setClientEmail("client@example.com");r.setCleanerId(22L);r.setCleanerEmail("cleaner@example.com");r.setAgreedAmountCents(5_000L);r.setCurrency("eur");r.setStatus("SCHEDULED");return r;}
 private Payment payment(String status){Payment p=new Payment();p.setId(7L);p.setReservationId(42L);p.setAmountCents(5_000L);p.setCurrency("eur");p.setStripePaymentIntentId("pi_existing");p.setStatus(status);return p;}
 private static class Deps{final PaymentRepository payments=mock(PaymentRepository.class);final ReservationRepository reservations=mock(ReservationRepository.class);final JobRepository jobs=mock(JobRepository.class);final StripeGateway stripe=mock(StripeGateway.class);final MarketplaceNotificationService notifications=mock(MarketplaceNotificationService.class);final MarketplacePaymentPolicy policy=mock(MarketplacePaymentPolicy.class);final ConnectAccountService connect=mock(ConnectAccountService.class);final MarketplaceSettlementService settlements=mock(MarketplaceSettlementService.class);}
}
