package com.clean.it.service.impl;

import com.clean.it.domain.Payment;import com.clean.it.domain.Reservation;import com.clean.it.dto.AppDtos.PaymentRequest;import com.clean.it.repository.JobRepository;import com.clean.it.repository.PaymentRepository;import com.clean.it.repository.ReservationRepository;import com.clean.it.service.StripeGateway;import com.clean.it.service.StripeGateway.IntentSnapshot;import com.clean.it.service.StripeGateway.RefundSnapshot;import org.junit.jupiter.api.Test;import java.util.Optional;import static org.assertj.core.api.Assertions.assertThat;import static org.mockito.Mockito.*;

class PaymentServiceImplTest {
 @Test void createsAnIntentFromTheFrozenReservationPriceWithAStableIdempotencyKey(){PaymentRepository payments=mock(PaymentRepository.class);ReservationRepository reservations=mock(ReservationRepository.class);JobRepository jobs=mock(JobRepository.class);StripeGateway stripe=mock(StripeGateway.class);Reservation reservation=reservation(42L);when(reservations.findLockedById(42L)).thenReturn(Optional.of(reservation));when(payments.findFirstByReservationId(42L)).thenReturn(Optional.empty());when(stripe.isConfigured()).thenReturn(true);when(stripe.publishableKey()).thenReturn("pk_test_123");when(stripe.createPaymentIntent(5_000L,"eur",42L,"reservation:42:payment-intent:v1")).thenReturn(new IntentSnapshot("pi_123","secret_123","requires_payment_method","{}"));when(payments.save(org.mockito.ArgumentMatchers.any(Payment.class))).thenAnswer(i->i.getArgument(0));PaymentRequest request=new PaymentRequest();request.setReservationId(42L);var response=new PaymentServiceImpl(payments,reservations,jobs,stripe).createPaymentIntent(11L,request);assertThat(response.getAmountCents()).isEqualTo(5_000L);assertThat(response.getCurrency()).isEqualTo("eur");assertThat(response.getClientSecret()).isEqualTo("secret_123");verify(stripe).createPaymentIntent(5_000L,"eur",42L,"reservation:42:payment-intent:v1");}
 @Test void reusesTheExistingIntentInsteadOfCreatingAnotherCharge(){PaymentRepository payments=mock(PaymentRepository.class);ReservationRepository reservations=mock(ReservationRepository.class);JobRepository jobs=mock(JobRepository.class);StripeGateway stripe=mock(StripeGateway.class);Reservation reservation=reservation(42L);Payment existing=payment("requires_payment_method");existing.setClientSecret("secret_existing");when(reservations.findLockedById(42L)).thenReturn(Optional.of(reservation));when(payments.findFirstByReservationId(42L)).thenReturn(Optional.of(existing));when(stripe.isConfigured()).thenReturn(true);when(stripe.publishableKey()).thenReturn("pk_test_123");PaymentRequest request=new PaymentRequest();request.setReservationId(42L);var response=new PaymentServiceImpl(payments,reservations,jobs,stripe).createPaymentIntent(11L,request);assertThat(response.getPaymentId()).isEqualTo(7L);assertThat(response.getClientSecret()).isEqualTo("secret_existing");verify(stripe,never()).createPaymentIntent(anyLong(),anyString(),anyLong(),anyString());}
 @Test void successfulPaymentIsRefundedOnReservationCancellation(){PaymentRepository payments=mock(PaymentRepository.class);ReservationRepository reservations=mock(ReservationRepository.class);JobRepository jobs=mock(JobRepository.class);StripeGateway stripe=mock(StripeGateway.class);Payment payment=payment("succeeded");when(payments.findFirstByReservationId(42L)).thenReturn(Optional.of(payment));when(stripe.isConfigured()).thenReturn(true);when(stripe.refundPaymentIntent("pi_existing","reservation:42:refund:v1")).thenReturn(new RefundSnapshot("re_1","succeeded","{}"));new PaymentServiceImpl(payments,reservations,jobs,stripe).cancelOrRefundReservationPayment(42L);assertThat(payment.getStatus()).isEqualTo("refunded");verify(payments).save(payment);}
 private Reservation reservation(long id){Reservation r=new Reservation();r.setId(id);r.setJobId(3L);r.setClientId(11L);r.setClientEmail("client@example.com");r.setCleanerId(22L);r.setCleanerEmail("cleaner@example.com");r.setAgreedAmountCents(5_000L);r.setCurrency("eur");r.setStatus("SCHEDULED");return r;}
 private Payment payment(String status){Payment p=new Payment();p.setId(7L);p.setReservationId(42L);p.setAmountCents(5_000L);p.setCurrency("eur");p.setStripePaymentIntentId("pi_existing");p.setStatus(status);return p;}
}
