import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useState } from 'react';
import { useApi } from '../../api';
import { useAuth } from '../../auth';
import { dateTime, money } from '../../shared/format';
import { Empty, ErrorMessage, PageHeader } from '../../shared/ui';
import type { AdminEntityType, AdminSearchItem } from '../../types';

const TYPES:AdminEntityType[]=['USER','CLEANER','JOB','RESERVATION','PAYMENT','REVIEW'];
const LABEL:Record<AdminEntityType,string>={USER:'Usuarios',CLEANER:'Cleaners',JOB:'Jobs',RESERVATION:'Reservas',PAYMENT:'Pagos',REVIEW:'Reseñas'};

export function AdminPage(){
 const auth=useAuth();const api=useApi();const qc=useQueryClient();const[type,setType]=useState<AdminEntityType>('RESERVATION');const[q,setQ]=useState('');const[reason,setReason]=useState('');const[selected,setSelected]=useState<AdminSearchItem>();
 const allowed=auth.roles.includes('ADMIN');
 const search=useQuery({queryKey:['admin','search',type,q],queryFn:()=>api.admin.search(type,q),enabled:allowed});
 const timeline=useQuery({queryKey:['admin','timeline',selected?.id],queryFn:()=>api.admin.timeline(Number(selected!.id)),enabled:allowed&&selected?.type==='RESERVATION'});
 const action=useMutation({mutationFn:async(input:{kind:'block'|'unblock'|'hide'|'show'|'cancel'|'refund';item:AdminSearchItem})=>{if(!reason.trim())throw new Error('Escribe un motivo para la auditoría.');const id=Number(input.item.id);if(!window.confirm(`Confirmar ${input.kind} sobre ${input.item.type} #${id}?`))throw new Error('Operación cancelada');switch(input.kind){case'block':return api.admin.blockUser(id,reason);case'unblock':return api.admin.unblockUser(id,reason);case'hide':return api.admin.moderateReview(id,'HIDDEN',reason);case'show':return api.admin.moderateReview(id,'VISIBLE',reason);case'cancel':return api.admin.cancelReservation(id,reason);case'refund':return api.admin.refundReservation(id,reason);}},onSuccess:()=>{setReason('');void qc.invalidateQueries({queryKey:['admin']});}});
 if(!allowed)return <section className="page narrow"><PageHeader eyebrow="Operaciones" title="Acceso restringido">Esta consola requiere el rol ADMIN emitido por el proveedor OIDC.</PageHeader></section>;
 const results=search.data??[];
 return <section className="page"><PageHeader eyebrow="Operaciones" title="Administración">Busca entidades, modera con trazabilidad y reconcilia reservas con Stripe sin editar la base de datos.</PageHeader>
  <div className="split-layout"><div className="stack">
   <div className="panel"><div className="toolbar"><select className="input" value={type} onChange={e=>{setType(e.target.value as AdminEntityType);setSelected(undefined);}}>{TYPES.map(t=><option key={t} value={t}>{LABEL[t]}</option>)}</select><input className="input" value={q} onChange={e=>setQ(e.target.value)} placeholder="ID, email, estado o texto"/></div>{search.error&&<ErrorMessage error={search.error}/>} {!search.isLoading&&results.length===0&&<Empty>Sin resultados.</Empty>}<div className="stack">{results.map(item=><button type="button" className="panel admin-result" key={`${item.type}-${item.id}`} onClick={()=>setSelected(item)}><div className="card-head"><strong>{item.primaryText||`${item.type} #${item.id}`}</strong><span className="tag">{item.status||'—'}</span></div><small className="muted">{item.type} #{item.id} · {item.secondaryText||'—'}{item.occurredAt?` · ${dateTime(item.occurredAt)}`:''}</small></button>)}</div></div>
   {timeline.data&&<div className="panel"><span className="eyebrow">Timeline</span><h2>Reserva #{timeline.data.reservationId}</h2><div className="detail-grid"><span><small>Reserva</small>{timeline.data.reservationStatus}</span><span><small>Pago</small>{timeline.data.paymentStatus??'Sin pago'}</span><span><small>Settlement</small>{timeline.data.settlement?.status??'No Connect'}</span></div><div className="stack">{timeline.data.events.map((event,index)=><div className="notice" key={`${event.type}-${index}`}><strong>{event.type}</strong><div className="muted">{event.status} · {dateTime(event.occurredAt)}</div>{event.detail&&<small>{event.detail}</small>}</div>)}</div>{timeline.data.settlement&&<><h3>Conciliación del servicio</h3><div className="detail-grid"><span><small>Bruto</small>{money(timeline.data.settlement.grossCents,timeline.data.settlement.currency)}</span><span><small>Fee plataforma</small>{money(timeline.data.settlement.platformFeeCents,timeline.data.settlement.currency)}</span><span><small>Neto profesional</small>{money(timeline.data.settlement.providerAmountCents,timeline.data.settlement.currency)}</span></div><small className="muted">PI {timeline.data.settlement.stripePaymentIntentId??'—'} · Charge {timeline.data.settlement.stripeChargeId??'—'} · Transfer {timeline.data.settlement.stripeTransferId??'—'}</small><h3>Payouts recientes de la cuenta conectada</h3><p className="muted">Stripe puede agrupar varios transfers en un payout bancario; esta lista pertenece a la cuenta, no exclusivamente a esta reserva.</p>{timeline.data.connectedAccountPayouts.length===0?<Empty>Aún no hay payouts registrados.</Empty>:<div className="table-card"><div className="table-scroll"><table><thead><tr><th>Payout</th><th>Importe</th><th>Estado</th><th>Llegada</th></tr></thead><tbody>{timeline.data.connectedAccountPayouts.map(p=><tr key={p.id}><td>{p.stripePayoutId}</td><td>{money(p.amountCents,p.currency)}</td><td>{p.status}</td><td>{dateTime(p.arrivalAt)}</td></tr>)}</tbody></table></div></div>}</>}</div>}
  </div><aside className="panel form-panel"><span className="eyebrow">Acción auditada</span><h2>{selected?`${selected.type} #${selected.id}`:'Selecciona un resultado'}</h2><p className="muted">Las acciones financieras y de moderación requieren motivo y generan una clave idempotente.</p><label>Motivo<textarea className="input textarea" value={reason} onChange={e=>setReason(e.target.value)} placeholder="Motivo operativo / ticket de soporte"/></label>{selected?.type==='USER'&&<div className="actions"><button className="button secondary" disabled={!reason.trim()||action.isPending} onClick={()=>action.mutate({kind:selected.status==='BLOCKED'?'unblock':'block',item:selected})}>{selected.status==='BLOCKED'?'Desbloquear':'Bloquear'}</button></div>}{selected?.type==='REVIEW'&&<div className="actions"><button className="button secondary" disabled={!reason.trim()||action.isPending} onClick={()=>action.mutate({kind:selected.status==='HIDDEN'?'show':'hide',item:selected})}>{selected.status==='HIDDEN'?'Restaurar reseña':'Ocultar reseña'}</button></div>}{selected?.type==='RESERVATION'&&<div className="actions"><button className="button secondary" disabled={!reason.trim()||action.isPending} onClick={()=>action.mutate({kind:'cancel',item:selected})}>Cancelar reserva</button><button className="button secondary" disabled={!reason.trim()||action.isPending} onClick={()=>action.mutate({kind:'refund',item:selected})}>Reembolsar pago</button></div>}{action.error&&<ErrorMessage error={action.error}/>} {timeline.error&&<ErrorMessage error={timeline.error}/>}</aside></div>
 </section>;
}
