package com.clean.it.dto;

import jakarta.validation.constraints.NotBlank;import jakarta.validation.constraints.NotNull;import jakarta.validation.constraints.Size;import java.time.Instant;
public final class NotificationDtos {private NotificationDtos(){}
 public static class PreferenceResponse{private boolean emailEnabled,pushEnabled;public boolean isEmailEnabled(){return emailEnabled;}public void setEmailEnabled(boolean v){emailEnabled=v;}public boolean isPushEnabled(){return pushEnabled;}public void setPushEnabled(boolean v){pushEnabled=v;}}
 public static class PreferenceRequest{private boolean emailEnabled=true,pushEnabled=true;public boolean isEmailEnabled(){return emailEnabled;}public void setEmailEnabled(boolean v){emailEnabled=v;}public boolean isPushEnabled(){return pushEnabled;}public void setPushEnabled(boolean v){pushEnabled=v;}}
 public static class NotificationResponse{private Long id;private String eventType,channel,subject,body,status;private Instant createdAt,sentAt;public Long getId(){return id;}public void setId(Long v){id=v;}public String getEventType(){return eventType;}public void setEventType(String v){eventType=v;}public String getChannel(){return channel;}public void setChannel(String v){channel=v;}public String getSubject(){return subject;}public void setSubject(String v){subject=v;}public String getBody(){return body;}public void setBody(String v){body=v;}public String getStatus(){return status;}public void setStatus(String v){status=v;}public Instant getCreatedAt(){return createdAt;}public void setCreatedAt(Instant v){createdAt=v;}public Instant getSentAt(){return sentAt;}public void setSentAt(Instant v){sentAt=v;}}
 public static class PushSubscriptionRequest{@NotBlank @Size(max=2048) private String endpoint;@NotNull private Keys keys;public String getEndpoint(){return endpoint;}public void setEndpoint(String v){endpoint=v;}public Keys getKeys(){return keys;}public void setKeys(Keys v){keys=v;}public static class Keys{@NotBlank @Size(max=255) private String p256dh;@NotBlank @Size(max=255) private String auth;public String getP256dh(){return p256dh;}public void setP256dh(String v){p256dh=v;}public String getAuth(){return auth;}public void setAuth(String v){auth=v;}}}
 public static class PushUnsubscribeRequest{@NotBlank @Size(max=2048) private String endpoint;public String getEndpoint(){return endpoint;}public void setEndpoint(String v){endpoint=v;}}
 public static class PushConfigResponse{private boolean enabled;private String publicKey;public boolean isEnabled(){return enabled;}public void setEnabled(boolean v){enabled=v;}public String getPublicKey(){return publicKey;}public void setPublicKey(String v){publicKey=v;}}
}
