package com.clean.it.service.impl;

import com.clean.it.domain.Job;import com.clean.it.domain.JobStatus;import com.clean.it.dto.JobDtos.CreateJobRequest;import com.clean.it.dto.JobDtos.JobResponse;import com.clean.it.repository.JobRepository;import com.clean.it.service.JobService;import com.clean.it.service.MarketplaceNotificationService;import com.clean.it.util.RedisLockService;import com.clean.it.websocket.JobNotificationService;import org.slf4j.Logger;import org.slf4j.LoggerFactory;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.time.Duration;import java.util.List;import java.util.stream.Collectors;

@Service public class JobServiceImpl implements JobService {
 private static final Logger log=LoggerFactory.getLogger(JobServiceImpl.class);private final JobRepository jobs;private final RedisLockService locks;private final JobNotificationService live;private final MarketplaceNotificationService notifications;
 public JobServiceImpl(JobRepository jobs,RedisLockService locks,JobNotificationService live,MarketplaceNotificationService notifications){this.jobs=jobs;this.locks=locks;this.live=live;this.notifications=notifications;}
 @Override @Transactional public JobResponse createJob(Long clientId,String email,CreateJobRequest req){Job j=new Job();j.setClientId(clientId);j.setClientEmail(email);j.setTitle(req.getTitle()!=null&&!req.getTitle().isBlank()?req.getTitle():null);j.setDescription(req.getDescription());j.setPriceCents(req.getPriceCents());j.setStatus(JobStatus.OPEN);Job saved=jobs.save(j);publish(toDto(saved));return toDto(saved);}
 @Override public List<JobResponse> listOpenJobs(){return jobs.findByStatus(JobStatus.OPEN).stream().map(this::toDto).collect(Collectors.toList());}
 @Override @Transactional public JobResponse acceptJob(Long cleanerId,String cleanerEmail,Long jobId){String key="job:lock:"+jobId,token=null;try{token=locks.tryLock(key,Duration.ofSeconds(5));if(token==null)throw new IllegalStateException("Could not acquire lock, try again");Job job=jobs.findByIdForUpdate(jobId).orElseThrow(()->new IllegalArgumentException("Job not found"));if(job.getStatus()!=JobStatus.OPEN)throw new IllegalStateException("Job is not open");if(jobs.existsByCleanerIdAndStatusIn(cleanerId,List.of(JobStatus.ACCEPTED,JobStatus.IN_PROGRESS)))throw new IllegalStateException("Cleaner already has an active job");job.setCleanerId(cleanerId);job.setCleanerEmail(cleanerEmail);job.setStatus(JobStatus.ACCEPTED);Job saved=jobs.save(job);notifications.jobAccepted(saved);JobResponse response=toDto(saved);publish(response);return response;}finally{try{locks.releaseLock(key,token);}catch(Exception e){log.warn("Failed to release lock {}",key,e);}}}
 private void publish(JobResponse response){try{live.publishJobUpdate(response);}catch(Exception e){log.error("Failed to publish job update for job id={}",response.getId(),e);}}
 private JobResponse toDto(Job j){JobResponse d=new JobResponse();d.setId(j.getId());d.setClientEmail(j.getClientEmail());d.setCleanerEmail(j.getCleanerEmail());d.setStatus(j.getStatus().name());d.setTitle(j.getTitle());d.setDescription(j.getDescription());d.setPriceCents(j.getPriceCents());d.setCreatedAt(j.getCreatedAt());d.setUpdatedAt(j.getUpdatedAt());return d;}
}
