package com.clean.it.service.impl;

import com.clean.it.domain.Job;import com.clean.it.domain.Payment;import com.clean.it.domain.Reservation;import com.clean.it.dto.AppDtos.PaymentRequest;import com.clean.it.dto.AppDtos.PaymentResponse;import com.clean.it.repository.JobRepository;import com.clean.it.repository.PaymentRepository;import com.clean.it.repository.ReservationRepository;import com.clean.it.service.MarketplaceNotificationService;import com.clean.it.service.PaymentService;import com.clean.it.service.StripeGateway;import com.clean.it.service.StripeGateway.IntentSnapshot;import com.clean.it.service.StripeGateway.RefundSnapshot;import org.slf4j.Logger;import org.slf4j.LoggerFactory;import org.springframework.security.access.AccessDeniedException;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.util.Locale;import java.util.Objects;import java.util.Set;

@Service public class PaymentServiceImpl implements PaymentService {
 private static final Logger log=LoggerFactory.getLogger(PaymentServiceImpl.class);private static final Set<String> TERMINAL=Set.of("canceled","refunded");private final PaymentRepository payments;private final ReservationRepository reservations;private final JobRepository jobs;private final StripeGateway stripe;private final MarketplaceNotificationService notifications;
 public PaymentServiceImpl(PaymentRepository payments,ReservationRepository reservations,JobRepository jobs,StripeGateway stripe,MarketplaceNotificationService notifications){this.payments=payments;this.reservations=reservations;this.jobs=jobs;this.stripe=stripe;this.notifications=notifications;}
 @Override @Transactional public PaymentResponse createPaymentIntent(Long userId,PaymentRequest req){Reservation r=reservations.findLockedById(req.getReservationId()).orElseThrow(()->new IllegalArgumentException("Reservation not found"));if(!Objects.equals(r.getClientId(),userId))throw new AccessDeniedException("Only the reservation client can create its payment");if("CANCELLED".equalsIgnoreCase(r.getStatus()))throw new IllegalStateException("Cancelled reservations cannot be paid");if(!stripe.isConfigured())throw new IllegalStateException("Stripe is not configured");freeze(r);Payment existing=payments.findFirstByReservationId(r.getId()).orElse(null);if(existing!=null&&existing.getStripePaymentIntentId()!=null){if(TERMINAL.contains(normalize(existing.getStatus())))throw new IllegalStateException("The reservation payment is no longer payable");if(existing.getClientSecret()==null||existing.getClientSecret().isBlank())existing=refresh(existing);return dto(existing);}String key="reservation:"+r.getId()+":payment-intent:v1";try{IntentSnapshot intent=stripe.createPaymentIntent(r.getAgreedAmountCents(),r.getCurrency(),r.getId(),key);Payment p=existing==null?new Payment():existing;p.setReservationId(r.getId());p.setAmountCents(r.getAgreedAmountCents());p.setCurrency(r.getCurrency());apply(p,intent);Payment saved=payments.save(p);r.setPaymentIntentId(intent.id());reservations.save(r);return dto(saved);}catch(RuntimeException e){log.error("Stripe failed to create a PaymentIntent for reservation {}",r.getId(),e);throw e;}}
 @Override @Transactional public void cancelOrRefundReservationPayment(Long reservationId){Payment p=payments.findFirstByReservationId(reservationId).orElse(null);if(p==null||p.getStripePaymentIntentId()==null||p.getStripePaymentIntentId().isBlank())return;if(!stripe.isConfigured())throw new IllegalStateException("Stripe is not configured, so an existing payment cannot be cancelled safely");String status=normalize(p.getStatus());if(TERMINAL.contains(status))return;if("succeeded".equals(status)){RefundSnapshot refund=stripe.refundPaymentIntent(p.getStripePaymentIntentId(),"reservation:"+reservationId+":refund:v1");p.setStatus("refunded");p.setRawJson(refund.rawJson());Payment saved=payments.save(p);reservations.findById(reservationId).ifPresent(r->notifications.paymentStatus(saved,r));return;}IntentSnapshot cancelled=stripe.cancelPaymentIntent(p.getStripePaymentIntentId());apply(p,cancelled);payments.save(p);}
 private void freeze(Reservation r){if(r.getAgreedAmountCents()!=null&&r.getAgreedAmountCents()>0&&r.getCurrency()!=null&&!r.getCurrency().isBlank())return;Job j=jobs.findById(r.getJobId()).orElseThrow(()->new IllegalStateException("Job linked to reservation not found"));long amount=j.getPriceCents()==null?0:j.getPriceCents();if(amount<=0)throw new IllegalStateException("Reservation has no valid payable amount");r.setAgreedAmountCents(amount);r.setCurrency("eur");reservations.save(r);}
 private Payment refresh(Payment p){IntentSnapshot intent=stripe.retrievePaymentIntent(p.getStripePaymentIntentId());apply(p,intent);return payments.save(p);}private void apply(Payment p,IntentSnapshot i){p.setStripePaymentIntentId(i.id());p.setClientSecret(i.clientSecret());p.setStatus(i.status());p.setRawJson(i.rawJson());}private String normalize(String s){return s==null?"":s.toLowerCase(Locale.ROOT);}private PaymentResponse dto(Payment p){PaymentResponse r=new PaymentResponse();r.setPaymentId(p.getId());r.setClientSecret(p.getClientSecret());r.setAmountCents(p.getAmountCents());r.setCurrency(p.getCurrency()==null?null:p.getCurrency().toLowerCase(Locale.ROOT));r.setStatus(p.getStatus());r.setPublishableKey(stripe.publishableKey());return r;}
}
