package com.clean.it.service.impl;

import com.clean.it.domain.Cleaner;import com.clean.it.domain.Reservation;import com.clean.it.domain.Review;import com.clean.it.dto.AppDtos.ReservationReviewRequest;import com.clean.it.dto.AppDtos.ReviewResponse;import com.clean.it.repository.CleanerRepository;import com.clean.it.repository.ReservationRepository;import com.clean.it.repository.ReviewRepository;import com.clean.it.service.MarketplaceNotificationService;import com.clean.it.service.ReviewService;import org.springframework.security.access.AccessDeniedException;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.util.List;import java.util.Objects;

@Service public class ReviewServiceImpl implements ReviewService {
 private final ReviewRepository reviews;private final ReservationRepository reservations;private final CleanerRepository cleaners;private final MarketplaceNotificationService notifications;
 public ReviewServiceImpl(ReviewRepository reviews,ReservationRepository reservations,CleanerRepository cleaners,MarketplaceNotificationService notifications){this.reviews=reviews;this.reservations=reservations;this.cleaners=cleaners;this.notifications=notifications;}
 @Override @Transactional public ReviewResponse addReviewForReservation(Long clientId,String clientEmail,Long reservationId,ReservationReviewRequest request){Reservation reservation=reservations.findLockedById(reservationId).orElseThrow(()->new IllegalArgumentException("Reservation not found"));if(!Objects.equals(reservation.getClientId(),clientId))throw new AccessDeniedException("Only the reservation client can review it");if(!"COMPLETED".equalsIgnoreCase(reservation.getStatus()))throw new IllegalStateException("A review can only be created after the reservation is completed");if(reviews.existsByReservationId(reservationId))throw new IllegalStateException("This reservation already has a review");Review review=new Review();review.setReservationId(reservationId);review.setCleanerId(reservation.getCleanerId());review.setCleanerEmail(reservation.getCleanerEmail());review.setClientId(clientId);review.setClientEmail(clientEmail);review.setRating(request.getRating());review.setComment(request.getComment());Review saved=reviews.save(review);refreshCleanerRating(reservation.getCleanerId());notifications.reviewReceived(saved);return toDto(saved);}
 @Override @Transactional(readOnly=true) public List<ReviewResponse> listReviews(String email){Cleaner cleaner=cleaners.findByEmailIgnoreCase(email).orElseThrow(()->new IllegalArgumentException("Cleaner profile not found"));return reviews.findByCleanerIdOrderByCreatedAtDesc(cleaner.getUserId()).stream().map(this::toDto).toList();}
 private void refreshCleanerRating(Long cleanerId){Double avg=reviews.averageRating(cleanerId);cleaners.findFirstByUserId(cleanerId).ifPresent(c->{c.setRating(avg==null?0.0:Math.round(avg*100.0)/100.0);cleaners.save(c);});}
 private ReviewResponse toDto(Review r){ReviewResponse x=new ReviewResponse();x.setId(r.getId());x.setReservationId(r.getReservationId());x.setCleanerEmail(r.getCleanerEmail());x.setClientEmail(r.getClientEmail());x.setRating(r.getRating());x.setComment(r.getComment());x.setCreatedAt(r.getCreatedAt());return x;}
}
